[tool]
name = "actionlint"
category = "lint"
homepage = "https://github.com/rhysd/actionlint"
docs = "https://github.com/rhysd/actionlint/blob/main/docs/usage.md"
repo = "https://github.com/rhysd/actionlint"
description = "Static analysis for GitHub Actions workflows"

[detect]
dependencies = ["rhysd/actionlint"]

[commands]
run = "actionlint"

[taxonomy]
role = ["linter"]
