[tool]
name = "cljfmt"
category = "format"
default = true
homepage = "https://github.com/weavejester/cljfmt"
docs = "https://github.com/weavejester/cljfmt#readme"
repo = "https://github.com/weavejester/cljfmt"
description = "Clojure code formatter"

[detect]
ecosystems = ["clojure"]
[detect.file_contains]
"project.clj" = ["cljfmt"]
"deps.edn" = ["cljfmt"]

[commands]
run = "lein cljfmt check"
alternatives = ["lein cljfmt fix"]
