[tool]
name = "RubyGems"
category = "package_manager"
homepage = "https://rubygems.org"
docs = "https://guides.rubygems.org/command-reference/"
repo = "https://github.com/ruby/rubygems"
description = "Ruby package manager"

[detect]
files = ["*.gemspec", "**/*.gemspec"]
dependencies = ["hoe"]
ecosystems = ["ruby"]

[detect.file_contains]
"Rakefile" = ["Hoe.spec", "Hoe.new", "Gem::PackageTask"]
"rakefile" = ["Hoe.spec", "Hoe.new", "Gem::PackageTask"]
"Rakefile.rb" = ["Hoe.spec", "Hoe.new", "Gem::PackageTask"]
"rakefile.rb" = ["Hoe.spec", "Hoe.new", "Gem::PackageTask"]

[config]
files = ["*.gemspec", "**/*.gemspec", ".gemrc"]

[taxonomy]
role = ["package-manager"]
