[tool]
name = "Dialyxir"
category = "typecheck"
default = true
homepage = "https://github.com/jeremyjh/dialyxir"
docs = "https://hexdocs.pm/dialyxir"
repo = "https://github.com/jeremyjh/dialyxir"
description = "Dialyzer wrapper for Elixir"

[detect]
dependencies = ["dialyxir"]
ecosystems = ["elixir"]

[commands]
run = "mix dialyzer"
