[tool]
name = "V"
category = "language"
homepage = "https://vlang.io"
docs = "https://docs.vlang.io"
repo = "https://github.com/vlang/v"
description = "Simple, fast compiled language"

[detect]
files = ["v.mod"]
ecosystems = ["v"]
